### ISSUE TITLE
.NET Core/.NET 5.0

### ISSUE THREAD

**Issue by mjhoffmeister** [pulpfreepress/ERCOTSampleCode#1]
I'm curious as to whether you've been able to make this work with .NET Core or .NET 5.0. I haven't been able to get calls to the ERCOT API working on those platforms.

**Comment by pulpfreepress** [comment]
I haven’t tried on .NET Core, though some parts of the library will work, but the important thing to note is that ERCOT uses an older security library which must be installed and added to the project resources. Also, I could never connect to their “testing” endpoint regardless of how hard I tried. One needs an ERCOT client account and a valid client cert.  the make sure you have generated the ERCOT services WSDL from the proper endpoint.

It’s a real Kabuki dance to get it to work,  but once you can successfully retrieve the system status, it starts to make sense.

Good luck!

**Comment by mjhoffmeister** [comment]
Yeah, I can get it to work in .NET Framework with a somewhat complicated `system.serviceModel` config, but that route doesn't an option in .NET Core or .NET 5.0 because the needed library isn't available.

Anyway, I was just curious. Thanks for the response!
